### ISSUE TITLE
Corrupt/non-readable .png files being produced.

### ISSUE THREAD

**Issue by HaniiPuppy** [nsimplex/ktools#1]
I followed the instructions here: http://albinofruit.com/2014/08/guide-modding-dont-starve-mac/

.png files produced from .tex files using the ktech tool seem to be completely unreadable. I've tried opening them in different image viewers/editors, using .tex files from different mods, and using different decompressors to decompress the files the .tex files are in, along with using uncompressed .tex files in the mods' root folders.

I can provide a .tex file and the result of trying to convert it, if you'd like.

**Comment by nsimplex** [comment]
The blog post linked is dead. Please provide the terminal output as well as sample files showcasing the issue and I'll reopen the issue.
