### ISSUE TITLE
FYI: Arch Linux pkgbuild

### ISSUE THREAD

**Issue by jleclanche** [nsimplex/ktools#2]
This is a really nice tool so I made a PKGBUILD for it, I figured you might want to know

https://aur.archlinux.org/packages/ktools-git

**Comment by jleclanche** [comment]
One thing that would be nice in order to get versioning is if you would tag releases with `git tag -fam "Release x.y.z" x.y.z` (or -fsm for pgp-signed) :) But that's not really necessary

**Comment by nsimplex** [comment]
I really appreciate the PKGBUILD, and not only because I'm an Arch Linux user myself. I've tagged the latest release, 4.3.0, which also includes important bugfixes.

Though, since this isn't quite an 'issue', I'm closing it.
